version: '3.8'

services:
  dns-update-service:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=5000
      - FLASK_DEBUG=false
      - AWS_DEFAULT_REGION=us-east-1
      # Required DNS configuration
      - HOSTED_ZONE_ID=${HOSTED_ZONE_ID}
      - DOMAIN_NAME=${DOMAIN_NAME}
      # IP validation configuration
      - ENABLE_IP_VALIDATION=${ENABLE_IP_VALIDATION:-true}
      - ALLOWED_IPS=${ALLOWED_IPS:-}
      - ALLOWED_SUBNETS=${ALLOWED_SUBNETS:-}
      # Password authentication configuration
      - ENABLE_PASSWORD_AUTH=${ENABLE_PASSWORD_AUTH:-true}
      - AUTH_PASSWORD=${AUTH_PASSWORD:-}
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY:-dns-update-secret-key-change-in-production}
      # AWS credentials should be set via environment variables or mounted secrets
      # - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      # - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
      # Mount AWS credentials if using file-based authentication
      # - ~/.aws:/home/app/.aws:ro
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 